### ISSUE TITLE
learner emails who have chosen "opt in" for marketing

### ISSUE THREAD

**Issue by suzanneharrison** [dlab-berkeley/BerkeleyX-support#10]
Could I get a report for the emails of students who have chosen "opt in" to receive marketed information about UCB programs for the Solving Public Policy Problems: UC Berkeley’s Eightfold Path MOOC.

The list can be found in the package being sent. Here's some info on where to find them:
http://edx.readthedocs.org/en/latest/internal_data_formats/institution_data.html#email-opt-in-report

It's a file called :  {org}-email_opt_in-{site}-analytics.csv

**Comment by davclark** [comment]
Acknowledging this request for now. I'll see if I can get to it this week.

**Comment by suzanneharrison** [comment]
Thanks, Dav!

Suzanne

On Feb 1, 2016, at 7:03 PM, Dav Clark notifications@github.com wrote:

Acknowledging this request for now. I'll see if I can get to it this week.

**Comment by suzanneharrison** [comment]
Hi Dav,

I added a new request I've gotten for learner emails for ALL BerkeleyX courses (not just the "opt in" learner emails from Solving Public Policy Problems: UC Berkeley’s Eightfold Path MOOC).  I just wanted to call out here on this ticket request in case there was anything that could save you time to cover data pulling for both.

Thanks,
Suzanne

**Comment by davclark** [comment]
I asked if this is closed in an email to @suzanneharrison. Hopefully this is solved enough!
