### ISSUE TITLE
New "opt in" learner email request

### ISSUE THREAD

**Issue by suzanneharrison** [dlab-berkeley/BerkeleyX-support#11]
Hi Dav,
Could I get a report for the emails of students who have chosen "opt in" to receive marketed information about UCB programs.  This request is for **all BerkeleyX** students/courses.  **(Note: my previous request is for that particular course only).**

The list can be found in the package being sent. Here's some info on where to find them:
http://edx.readthedocs.org/en/latest/internal_data_formats/institution_data.html#email-opt-in-report

It's a file called : {org}-email_opt_in-{site}-analytics.csv

**Comment by davclark** [comment]
Send email to @suzanneharrison
