### ISSUE TITLE
adding amcross@berkeley.edu to BerkeleyX-support

### ISSUE THREAD

**Issue by suzanneharrison** [dlab-berkeley/BerkeleyX-support#12]
Hi Dav,

Could you add amcross@berkeley.edu to BerkeleyX-support so she can submit data requests for me?  She created an account on GitHub already. Can I do this or do you have to?

Thank you!
Suzanne

**Comment by davclark** [comment]
I think this person should be able to create new issues by going to this page:

https://github.com/dlab-berkeley/BerkeleyX-support/issues

If not, then please have them get in touch. Also please provide the github user account!
