### ISSUE TITLE
Enrollment numbers for Suzanne Watson

### ISSUE THREAD

**Issue by davclark** [dlab-berkeley/BerkeleyX-support#5]
From Suzanne:

> Could I get enrollment numbers for the following courses?  If you have info on verified, initial enrollments, completions, etc that would be great.  Let me know if you need more info from me.  THanks!!

| Course ID | Description | Faculty Names |
| --- | --- | --- |
| EE40LX | Electronic Interfaces: Bridging the Physical and Digital Worlds | Tom Zajdel |
| ColWri3.3x | "Frankenstein; Or, The Modern Prometheus" by Shelley: BerkeleyX Book Club | Maggie Sokolik |
| ColWri2.2x | English Grammar and Essay Writing | Maggie Sokolik |
| CS188.1x | Artificial Intelligence | Pieter Abbeel, Dan Klein |
| J4SC101x | Journalism for Social Change | Daniel Heimpel |
| ColWri2.3x | Principles of Written English, Part 3 | Maggie Sokolik |
| CS190.1x | Scalable Machine Learning | Ameet Talwalkar |
| CS100.1x | Introduction to Big Data with Apache Spark | Anthony Joseph |
| ColWri3.2x | "Adventures of Huckleberry Finn" by Twain: BerkeleyX Book Club | Maggie Sokolik |
| ColWri3.5x | "Dubliners" by Joyce: BerkeleyX Book Club | Maggie Sokolik |

**Comment by davclark** [comment]
@deniederhut Suzanne wants this by end-of-week. Do you have bandwidth for this?

**Comment by deniederhut** [comment]
Probably. Is all the data on Mercury already?

**Comment by davclark** [comment]
I will happily take responsibility for getting the data.

**Comment by deniederhut** [comment]
I have a first draft of a notebook to create these data for Suzanne - will test as soon as data is available.

**Comment by davclark** [comment]
Done - some notes:
- It looks like J4SC lacks the final "x"
- Some courses have multiple terms. Probably best to report on them separately.

**Comment by deniederhut** [comment]
Report sent.
