### ISSUE TITLE
Full data export fro BJC.1x

### ISSUE THREAD

**Issue by davclark** [dlab-berkeley/BerkeleyX-support#7]
Via Suzanne Harrison on behalf of the BJC.1x instructor:

> I was looking for the full data export options that edx gives. (The general course log). I was hoping to be able to do some analysis work on this data set for a class this semester.
> 
> Course: BJC.1x

**Comment by davclark** [comment]
Clarification: This means the event data? If so, this should be straightforward to provide.

**Comment by davclark** [comment]
Also, what is the date range for events on this course?

**Comment by suzanneharrison** [comment]
Sept 3, through Oct 23.  Thanks!!

**Comment by suzanneharrison** [comment]
Hi I may have missed this but did you send me the data for this request?

thanks,
Suzanne

**Comment by davclark** [comment]
Ack - sorry. Too many balls in the air - folks are always welcome to ping
if I haven't given a timeline (and especially if I've exceeded a timeline
I've given).

Is Monday OK for this? And should I send to you, or directly to the course
instructor?

Mea culpa,
Dav

On Fri, Nov 13, 2015 at 11:58 AM, suzanneharrison notifications@github.com
wrote:

> Hi I may have missed this but did you send me the data for this request?
> 
> thanks,
> Suzanne
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dlab-berkeley/BerkeleyX-support/issues/7#issuecomment-156541831
> .

## 

Dav Clark
Data Scientist
Berkeley D-Lab + BIDS
bead.glass
917-544-8408

**Comment by suzanneharrison** [comment]
No problem at all!  Monday is fine. You can send to me.  Thanks and have a
great weekend!

Suzanne

​Suzanne Harrison
Director Course Design and Development
Berkeley Resource Center for Online Education
510.643.1488

**Comment by davclark** [comment]
Data sent to Suzanne via email.
