### ISSUE TITLE
BerkeleyX total courses total enrollments

### ISSUE THREAD

**Issue by suzanneharrison** [dlab-berkeley/BerkeleyX-support#8]
Could I please get total enrollments and total course numbers from 2013 - present for all BerkeleyX courses on edX's platform?  Just numbers and don't need break downs. Thanks!

**Comment by davclark** [comment]
It sounds like this is quite urgent, so I'll try to get these tomorrow. Not a guarantee, though!

**Comment by davclark** [comment]
There were 34 courses that had certificate files. CSV of those in your inbox!
