### ISSUE TITLE
BerkeleyX Enrollment Numbers for 1/2014 - 12/2014 and 1/2015 - 12/2015

### ISSUE THREAD

**Issue by suzanneharrison** [dlab-berkeley/BerkeleyX-support#9]
Could you pull data for me for enrollments for BerkeleyX courses that ran from January 1 2014 - December 31, 2014 and another grab from January 1 2015 - December 31, 2014?

Thanks!!
Suzanne

**Comment by davclark** [comment]
Just acknowledging this - I am just ramping back into things, and I'll plan to get this to you this week.

**Comment by suzanneharrison** [comment]
Thanks!

​Suzanne Harrison
Director Course Design and Development
Berkeley Resource Center for Online Education
510.643.1488

**Comment by davclark** [comment]
Hi again - just an update that I've had too many balls in the air, so
likely _this_ week. Hopefully early this week.

On Tue, Jan 19, 2016 at 11:54 AM, suzanneharrison notifications@github.com
wrote:

> Thanks!
> 
> ​Suzanne Harrison
> Director Course Design and Development
> Berkeley Resource Center for Online Education
> 510.643.1488
> 
> On Tue, Jan 19, 2016 at 11:43 AM, Dav Clark notifications@github.com
> wrote:
> 
> > Just acknowledging this - I am just ramping back into things, and I'll
> > plan to get this to you this week.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/dlab-berkeley/BerkeleyX-support/issues/9#issuecomment-172963816
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dlab-berkeley/BerkeleyX-support/issues/9#issuecomment-172967070
> .

## 

Dav Clark
Data Scientist
Berkeley D-Lab + BIDS
bead.glass
917-544-8408

**Comment by davclark** [comment]
Sent CSV by email. Sorry for the slowness!
